"""update model

Revision ID: 0c8b5f4574d0
Revises: f2be61740e29
Create Date: 2024-12-09 07:57:20.670975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0c8b5f4574d0'
down_revision: Union[str, None] = 'f2be61740e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('page', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('page', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('page', 'url')
    # ### end Alembic commands ###
